server:
  port: 8080
spring:
  application:
    name: api-gateway
logging:
  level:
    com.thd.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka